clc;clear all;
cfg = [];
if ~isfield(cfg, 'basetype'),         cfg.basetype       = 'HA';         end; basetype      = cfg.basetype;
if ~isfield(cfg, 'oddtype'),          cfg.oddtype        = 'FE';         end; oddtype       = cfg.oddtype;
folderBase      = 'Your Path/Data and Materials/';
filename = ['Info' basetype oddtype];
load(fullfile(folderBase,filename));
load(fullfile(folderBase,'EEG_freq'));
load(fullfile(folderBase,'hgsn2clusters_ROI.mat'),'hgsn2clusters');
chidx1 = hgsn2clusters.left_to;
chidx2 = hgsn2clusters.right_to;
chidx3 = hgsn2clusters.middle_occipital;
chpow1 = mean(InfoHAFE.powspctrm_snr_all_HAFE(:,chidx1,:),2);
chpow2 = mean(InfoHAFE.powspctrm_snr_all_HAFE(:,chidx2,:),2);
chpow3 = mean(InfoHAFE.powspctrm_snr_all_HAFE(:,chidx3,:),2);

chopw1_odd_occipital1 = chpow1(:,find(EEG_freq.freq == 1.2));
R.chopw1_odd_occipital1 = chopw1_odd_occipital1;
chopw1_odd_occipital2 = chpow1(:,find(EEG_freq.freq == 2.4));
R.chopw1_odd_occipital2 = chopw1_odd_occipital2;
chopw1_odd_occipital3 = chpow1(:,find(EEG_freq.freq == 3.6));
R.chopw1_odd_occipital3 = chopw1_odd_occipital3;
chopw1_odd_occipital4 = chpow1(:,find(EEG_freq.freq == 4.8));
R.chopw1_odd_occipital4 = chopw1_odd_occipital4;
chopw1_odd_occipital5 = chpow1(:,find(EEG_freq.freq == 7.2));
R.chopw1_odd_occipital5 = chopw1_odd_occipital5;

chopw2_odd_occipital1 = chpow2(:,find(EEG_freq.freq == 1.2));
R.chopw2_odd_occipital1 = chopw2_odd_occipital1;
chopw2_odd_occipital2 = chpow2(:,find(EEG_freq.freq == 2.4));
R.chopw2_odd_occipital2 = chopw2_odd_occipital2;
chopw2_odd_occipital3 = chpow2(:,find(EEG_freq.freq == 3.6));
R.chopw2_odd_occipital3 = chopw2_odd_occipital3;
chopw2_odd_occipital4 = chpow2(:,find(EEG_freq.freq == 4.8));
R.chopw2_odd_occipital4 = chopw2_odd_occipital4;
chopw2_odd_occipital5 = chpow2(:,find(EEG_freq.freq == 7.2));
R.chopw2_odd_occipital5 = chopw2_odd_occipital5;
 
chopw3_odd_occipital1 = chpow3(:,find(EEG_freq.freq == 1.2));
R.chopw3_odd_occipital1 = chopw3_odd_occipital1;
chopw3_odd_occipital2 = chpow3(:,find(EEG_freq.freq == 2.4));
R.chopw3_odd_occipital2 = chopw3_odd_occipital2;
chopw3_odd_occipital3 = chpow3(:,find(EEG_freq.freq == 3.6));
R.chopw3_odd_occipital3 = chopw3_odd_occipital3;
chopw3_odd_occipital4 = chpow3(:,find(EEG_freq.freq == 4.8));
R.chopw3_odd_occipital4 = chopw3_odd_occipital4;
chopw3_odd_occipital5 = chpow3(:,find(EEG_freq.freq == 7.2));
R.chopw3_odd_occipital5 = chopw3_odd_occipital5;
combined_matrix = [R.chopw1_odd_occipital1, R.chopw1_odd_occipital2, R.chopw1_odd_occipital3, R.chopw1_odd_occipital4,R.chopw1_odd_occipital5,R.chopw2_odd_occipital1, R.chopw2_odd_occipital2, R.chopw2_odd_occipital3, R.chopw2_odd_occipital4,R.chopw2_odd_occipital5,R.chopw3_odd_occipital1, R.chopw3_odd_occipital2, R.chopw3_odd_occipital3, R.chopw3_odd_occipital4, R.chopw3_odd_occipital5];
